- name : Configure SLA
  ios_config :
    src : "templates/sla_track_template.j2"
  register : pushed_config
  notify : save config

- name : displaying pushed SLA config
  debug : var=pushed_config.updates
  when : pushed_config.changed
