- name : Configure L3 interfaces
  hosts : spoke1-core
  gather_facts : false

  roles:
    - configure_interfaces


- name : configure routing
  hosts : spoke1-core
  gather_facts : false

  roles:
    - configure_routing
