- name : Configure L3 interfaces on spokes
  hosts : spoke-core
  gather_facts : false

  roles:
    - configure_interfaces

- name : Configure routing on spokes
  hosts : spoke-core
  gather_facts : false

  roles:
    - configure_routing

- name : Config ip sla and track on spokes
  hosts : spoke-core
  gather_facts : false

  roles :
    - config_sla_and_track

- name : Configure HSRP on spokes
  hosts : spoke-core
  gather_facts : false

  roles :
    - configure_hsrp
