- name : Configure L3 interfaces
  hosts : spoke1-core
  gather_facts : false

  roles:
    - configure_interfaces

- name : Configure routing
  hosts : spoke1-core
  gather_facts : false

  roles:
    - configure_routing

- name : Config ip sla and track
  hosts : spoke1-core
  gather_facts : false

  roles :
    - config_sla_and_track

- name : Configure HSRP
  hosts : spoke1-core
  gather_facts : false

  roles :
    - configure_hsrp
