- name : Configure L3 interfaces on spokes
  hosts : spoke-core
  gather_facts : false

  roles:
    - configure_interfaces

- name : Configure routing on spokes
  hosts : spoke-core
  gather_facts : false

  roles:
    - configure_routing

- name : Config ip sla and track on spokes
  hosts : spoke-core
  gather_facts : false

  roles :
    - configure_sla_and_track

- name : Configure HSRP on spokes
  hosts : spoke-core
  gather_facts : false

  roles :
    - configure_hsrp

- name : Configure L3 interfaces on hub
  hosts : hub-core
  gather_facts : false

  roles :
    - configure_interfaces

- name : Configure BGP on hub
  hosts : hub-core
  gather_facts : flase

  roles :
    - configure_bgp_hub

- name : Configure ip sla and track on hub
  hosts : hub-core
  gather_facts : false

  roles :
    - configure_sla_and_track

- name : Configure HSRP on hub
  hosts : hub-core
  gather_facts : false

  roles :
    - configure_hsrp
