- name: gather_facts
  ios_facts:
    gather_subset: all

- name: configure l3 Interfaces
  ios_config:
    src: "templates/l3_interfaces_template.j2"
  register: pushed_config
  notify: save config

- name: displaying pushed config
  debug: var=pushed_config.updates
  when: pushed_config.changed
