- name : config tunnel interfaces
  ios_config :
    src : "templates/tunnel_interfaces_template.j2"
  register : pushed_config
  notify : save config

- name : displaying pushed config
  debug : var=pushed_config.updates
  when : pushed_config.changed
