- name : Configure EIGRP
  ios_config :
    src : "templates/eigrp_template.j2"
  register : pushed_config
  notify : save config

- name : displaying pushed eigrp config
  debug : var=pushed_config.updates
  when : pushed_config.changed
