l3_interfaces:
  - interface_type : Ethernet
    interface_id : 0/0
    description : to secondary ISP
    ip_address : 155.1.24.2
    subnet_mask : 255.255.255.0
    prefix : 24
  - interface_type : Ethernet
    interface_id : 0/1
    description : to core1
    ip_address : 155.1.12.2
    subnet_mask : 255.255.255.0
    prefix : 24
  - interface_type : Ethernet
    interface_id : 0/2
    description : towards lan vlan 1
    ip_address : 155.1.1.2
    subnet_mask : 255.255.255.0
    prefix : 24
  - interface_type : Ethernet
    interface_id : 0/2.10
    description : towards lan vlan 10
    ip_address : 155.1.11.2
    subnet_mask : 255.255.255.0
    encapsulation : 10
    prefix : 24
  - interface_type : Ethernet
    interface_id : 0/2.100
    description : towards lan vlan 100
    ip_address : 155.1.101.2
    subnet_mask : 255.255.255.0
    encapsulation : 100
    prefix : 24

loopback_interfaces :
  - interface_type : Loopback
    interface_id : 0
    description : loopback 0 interface
    ip_address : 150.1.2.2
    subnet_mask : 255.255.255.255
    prefix : 32

sla_track :
  - sla_number : 1
    destination_ip : 155.1.24.4
    threshold : 100
    timeout : 200
    frequency : 1
    life : forever
    start_time : now
    track_number : 1
    track_type : reachability

hsrp_priority : 120

bgp :
  asnumber : 200
  neighbor :
    - neighbor_ip : 155.1.24.4
      remote_as : 100
      update_source : false
    - neighbor_ip : 150.1.1.1
      remote_as : 200
      update_source : true
      source_interface : Loopback0
