- name : configure hsrp
  ios_config :
    src : "templates/hsrp_template.j2"
  register : pushed_config
  notify : save config

- name : displaying pushed config
  debug : var=pushed_config.updates
  when : pushed_config.changed
  
