
- name : testing ios_commands
  hosts : routers
  gather_facts: false
  
  tasks :
    - name : show commands
      ios_command :
        commands :
          - show version
          - show cdp n
      register : show_result

    - name : debugging
      debug : var=show_result.stdout_lines
